### PR TITLE
hotfix: adding destination schema

### PR DESCRIPTION
**Pull request by stevensjcho**
# Description (개요) 

Hotfix: Adding description of destination schema to query API

## Keep in Mind

If you are creating a new statement, your first commit should always be a copy of the statement(model, ThanoSQL, function) template. This will allow reviewers to see what has been changed from the template, making the review process much more efficient.

## Type of change (작업사항)

Please delete options that are not relevant and check out the type of change.

- [ ] Model statmenet creation 
- [ ] ThanoSQL statmenet creation 
- [ ] Function statmenet creation 
- [ ] Model statement fix 
- [ ] ThanoSQL statement fix 
- [ ] Function statement fix 

Following templates can be found from the [Tech-wiki Docs](https://github.com/smartmind-team/tech-wiki/tree/main/project/thanosql/docs). 

## Writing Convention

Make sure to check out the [Writing Convention](https://github.com/smartmind-team/tech-wiki/blob/main/project/thanosql/docs/writing_convention.md). 

## Review Process

Review should be conducted by at least two people.

### CODE REVIEW

**Review by yeemh — APPROVED** [review]

**Comment by yeemh** [comment]
? 왜 갑자기 많은게 바뀐거죠

**Comment by stevensjcho** [comment]
> ? 왜 갑자기 많은게 바뀐거죠

아 제목에 WIP를 까먹고 안 적었네요. 이제 바뀔 것 없을 것 같습니다.

**Review by yeemh — APPROVED** [review]
바로 main으로 merge하고 배포하려는거 맞죠?

FAQ가 한글에는 들어가 있고 영문에는 빠져있네요
원래도 그렇게 되어있긴 했네요 🤔 
image
image

**Review by lazyduo — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
