### PR TITLE
Fix/delete table name

### PR DESCRIPTION
**Pull request by inwookie**
# Description (개요) 

1. `table_name` is no longer provided by one of the options for `CONVERT`, `PREDICT`, and `SEARCH`. 
2. `main` merged to align `develop` to `main`.

## Keep in Mind

If you are creating a new statement, your first commit should always be a copy of the statement(model, ThanoSQL, function) template. This will allow reviewers to see what has been changed from the template, making the review process much more efficient.

## Type of change (작업사항)

- [x] ThanoSQL statement fix 

Following templates can be found from the [Tech-wiki Docs](https://github.com/smartmind-team/tech-wiki/tree/main/project/thanosql/docs). 

## Writing Convention

Make sure to check out the [Writing Convention](https://github.com/smartmind-team/tech-wiki/blob/main/project/thanosql/docs/writing_convention.md). 

## Review Process

Review should be conducted by at least two people.

### CODE REVIEW

**Review by yeemh — APPROVED** [review]
Good Job

**Comment by lazyduo** [comment]
이 내용도 이 pr에 같이 껴 넣어주시겠어요?
https://github.com/smartmind-team/thanosql-docs/pull/198

**Comment by inwookie** [comment]
> #198 이 내용도 이 pr에 같이 껴 넣어주시겠어요?

https://github.com/smartmind-team/thanosql-docs/pull/198 -> 이 branch로 merge 했습니다.

**Comment by lazyduo** [comment]
@inwookie 아 이런방법이..

**Review by lazyduo — APPROVED** [review]

**Pull request merged**
